package com.sbit.model;
// Generated 06/11/2015 12:05:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CondicionIva generated by hbm2java
 */
@Entity
@Table(name = "condicion_iva", catalog = "sbit")
public class CondicionIva implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String condicionIva;
	private Set<Empresa> empresas = new HashSet<Empresa>(0);

	public CondicionIva() {
	}

	public CondicionIva(String condicionIva) {
		this.condicionIva = condicionIva;
	}

	public CondicionIva(String condicionIva, Set<Empresa> empresas) {
		this.condicionIva = condicionIva;
		this.empresas = empresas;
	}

	@Id

	@Column(name = "condicion_iva", unique = true, nullable = false, length = 25)
	public String getCondicionIva() {
		return this.condicionIva;
	}

	public void setCondicionIva(String condicionIva) {
		this.condicionIva = condicionIva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicionIva")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

}
