package com.sbit.model;
// Generated 06/11/2015 12:05:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "sbit")
public class Empresa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEmpresa;
	private CondicionIva condicionIva;
	private String nombre;
	private String domicilio;
	private String telefono;
	private String localidad;
	private String cuit;

	public Empresa() {
	}

	public Empresa(CondicionIva condicionIva, String nombre, String domicilio, String telefono, String localidad,
			String cuit) {
		this.condicionIva = condicionIva;
		this.nombre = nombre;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.localidad = localidad;
		this.cuit = cuit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_empresa", unique = true, nullable = false)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "condicion_iva")
	public CondicionIva getCondicionIva() {
		return this.condicionIva;
	}

	public void setCondicionIva(CondicionIva condicionIva) {
		this.condicionIva = condicionIva;
	}

	@Column(name = "nombre", length = 35)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "domicilio", length = 70)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "localidad", length = 45)
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "cuit", length = 45)
	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

}
