package com.sbit.model;
// Generated 06/11/2015 12:05:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoTicket generated by hbm2java
 */
@Entity
@Table(name = "estado_ticket", catalog = "sbit")
public class EstadoTicket implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String estado;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public EstadoTicket() {
	}

	public EstadoTicket(String estado) {
		this.estado = estado;
	}

	public EstadoTicket(String estado, Set<Ticket> tickets) {
		this.estado = estado;
		this.tickets = tickets;
	}

	@Id

	@Column(name = "estado", unique = true, nullable = false, length = 7)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoTicket")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
