package com.sbit.model;
// Generated 06/11/2015 12:05:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoMensaje generated by hbm2java
 */
@Entity
@Table(name = "estado_mensaje", catalog = "sbit")
public class EstadoMensaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String estado;
	private Set<Mensaje> mensajes = new HashSet<Mensaje>(0);

	public EstadoMensaje() {
	}

	public EstadoMensaje(String estado) {
		this.estado = estado;
	}

	public EstadoMensaje(String estado, Set<Mensaje> mensajes) {
		this.estado = estado;
		this.mensajes = mensajes;
	}

	@Id

	@Column(name = "estado", unique = true, nullable = false, length = 20)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoMensaje")
	public Set<Mensaje> getMensajes() {
		return this.mensajes;
	}

	public void setMensajes(Set<Mensaje> mensajes) {
		this.mensajes = mensajes;
	}

}
