package com.sbit.model;
// Generated 06/11/2015 12:05:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.sbit.enums.TipoMensaje;

import javafx.scene.control.TextArea;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "mensaje", catalog = "sbit")
public class Mensaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idmensaje;
	private EstadoMensaje estadoMensaje;
	private String mensaje;
	private Date fecha;

	@Transient
	private TextArea textArea;
	@Transient
	private TipoMensaje tipoMensaje;

	public Mensaje() {
		this.textArea = new TextArea();
	}

	public Mensaje(EstadoMensaje estadoMensaje, String mensaje, Date fecha) {
		this.estadoMensaje = estadoMensaje;
		this.textArea = new TextArea();
		this.mensaje = mensaje;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmensaje", unique = true, nullable = false)
	public Integer getIdmensaje() {
		return this.idmensaje;
	}

	public void setIdmensaje(Integer idmensaje) {
		this.idmensaje = idmensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado")
	public EstadoMensaje getEstadoMensaje() {
		return this.estadoMensaje;
	}

	public void setEstadoMensaje(EstadoMensaje estadoMensaje) {
		this.estadoMensaje = estadoMensaje;
	}

	@Column(name = "mensaje", length = 200)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public TextArea getTextArea() {
		return textArea;
	}

	public void setTextArea(TextArea textArea) {
		this.textArea = textArea;
	}

	public TipoMensaje getTipoMensaje() {
		return tipoMensaje;
	}

	public void setTipoMensaje(TipoMensaje tipoMensaje) {
		this.tipoMensaje = tipoMensaje;
	}

}
