package com.sbit.model;
// Generated 06/11/2015 12:05:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Problema generated by hbm2java
 */
@Entity
@Table(name = "problema", catalog = "sbit")
public class Problema implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idproblema;
	private String nombre;

	public Problema() {
	}

	public Problema(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproblema", unique = true, nullable = false)
	public Integer getIdproblema() {
		return this.idproblema;
	}

	public void setIdproblema(Integer idproblema) {
		this.idproblema = idproblema;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
